name: Hola mundo
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo, como estás?
      run: echo "::set-output name=respuesta::${MI_VARIABLE}"
